#!/usr/bin/env bash
set -e

: "${HELM_CHART_VERSION:=0.25.0}" # cloudnative-pg 1.26.1

helm repo add cnpg https://cloudnative-pg.github.io/charts
helm repo update

# Cache current chart defaults for reference and diff during upgrade
mkdir -p resources/values/cnpg
helm show values cnpg/cloudnative-pg \
	--version "$HELM_CHART_VERSION" \
	>resources/values/cnpg/defaults.yaml

# Pull down and modify templates
mkdir -p manifests/base
helm template cnpg cnpg/cloudnative-pg \
	--version "$HELM_CHART_VERSION" \
	--namespace cnpg \
	>manifests/base/cnpg.yaml
