#!/usr/bin/env bash
set -e

if [[ ! -d ~/.local/bin ]]; then
	echo "Requires ~/.local/bin"
	exit 1
fi

curl -sSfL \
	https://github.com/cloudnative-pg/cloudnative-pg/raw/main/hack/install-cnpg-plugin.sh | sudo sh -s -- -b ~/.local/bin

cat >~/.local/bin/kubectl_complete-cnpg <<EOF
#!/usr/bin/env sh

# Call the __complete command passing it all arguments
kubectl cnpg __complete "\$@"
EOF

chmod +x ~/.local/bin/kubectl_complete-cnpg
